namespace LocalCompanion.Localization;

/// <summary>VOICEVOX スタイル ID ごとの表示名（API の日本語名より優先）。</summary>
internal readonly record struct VoicevoxSpeakerStyleEntry(string Speaker, string Style);

internal static class VoicevoxSpeakerStyleCatalog
{
    private static readonly Dictionary<int, VoicevoxSpeakerStyleEntry> EnglishByStyleId = new()
    {
        [0] = new("Shikoku Metan", "Sweet"),
        [1] = new("Zundamon", "Sweet"),
        [2] = new("Shikoku Metan", "Normal"),
        [3] = new("Zundamon", "Normal"),
        [4] = new("Shikoku Metan", "Sexy"),
        [5] = new("Zundamon", "Sexy"),
        [6] = new("Shikoku Metan", "Tsundere"),
        [7] = new("Zundamon", "Tsundere"),
        [8] = new("Kasukabe Tsumugi", "Normal"),
        [9] = new("Namiura Ritsu", "Normal"),
        [10] = new("Amahare Hau", "Normal"),
        [11] = new("Gennno Takehiro", "Normal"),
        [12] = new("Shirakami Kotaro", "Normal"),
        [13] = new("Aoyama Ryusei", "Normal"),
        [14] = new("Meimei Himari", "Normal"),
        [15] = new("Kyushu Sora", "Sweet"),
        [16] = new("Kyushu Sora", "Normal"),
        [17] = new("Kyushu Sora", "Sexy"),
        [18] = new("Kyushu Sora", "Tsundere"),
        [19] = new("Kyushu Sora", "Whisper"),
        [20] = new("Mochiko-san", "Normal"),
        [21] = new("Kenzaki Mesuo", "Normal"),
        [22] = new("Zundamon", "Whisper"),
        [23] = new("WhiteCUL", "Normal"),
        [24] = new("WhiteCUL", "Happy"),
        [25] = new("WhiteCUL", "Sad"),
        [26] = new("WhiteCUL", "Scared"),
        [27] = new("Goki", "Human ver."),
        [28] = new("Goki", "Plushie ver."),
        [29] = new("Number Seven", "Normal"),
        [30] = new("Number Seven", "Announcement"),
        [31] = new("Number Seven", "Narration"),
        [32] = new("Shirakami Kotaro", "Cheerful"),
        [33] = new("Shirakami Kotaro", "Nervous"),
        [34] = new("Shirakami Kotaro", "Angry"),
        [35] = new("Shirakami Kotaro", "Scared"),
        [36] = new("Shikoku Metan", "Whisper"),
        [37] = new("Shikoku Metan", "Hushed"),
        [38] = new("Zundamon", "Hushed"),
        [39] = new("Gennno Takehiro", "Joy"),
        [40] = new("Gennno Takehiro", "Angry"),
        [41] = new("Gennno Takehiro", "Sad"),
        [42] = new("Chibishiki Ji", "Normal"),
        [43] = new("Sakuraka Miko", "Normal"),
        [44] = new("Sakuraka Miko", "Second form"),
        [45] = new("Sakuraka Miko", "Loli"),
        [46] = new("Sayo", "Normal"),
        [47] = new("Nurse Robo Type T", "Normal"),
        [48] = new("Nurse Robo Type T", "Relaxed"),
        [49] = new("Nurse Robo Type T", "Scared"),
        [50] = new("Nurse Robo Type T", "Secret talk"),
        [51] = new("Holy Knight Benio", "Normal"),
        [52] = new("Suzumatsu Akashi", "Normal"),
        [53] = new("Kigashima Sorin", "Normal"),
        [54] = new("Haruka Nana", "Normal"),
        [55] = new("Nekomata Al", "Normal"),
        [56] = new("Nekomata Al", "Calm"),
        [57] = new("Nekomata Al", "Upbeat"),
        [58] = new("Nekomata Bii", "Normal"),
        [59] = new("Nekomata Bii", "Calm"),
        [60] = new("Nekomata Bii", "Shy"),
        [61] = new("Chugoku Usagi", "Normal"),
        [62] = new("Chugoku Usagi", "Surprised"),
        [63] = new("Chugoku Usagi", "Timid"),
        [64] = new("Chugoku Usagi", "Exhausted"),
        [65] = new("Namiura Ritsu", "Queen"),
        [66] = new("Mochiko-san", "Sexy / Anko"),
        [67] = new("Kurita Maron", "Normal"),
        [68] = new("Ieltan", "Normal"),
        [69] = new("Manbetsu Hanamaru", "Normal"),
        [70] = new("Manbetsu Hanamaru", "Energetic"),
        [71] = new("Manbetsu Hanamaru", "Whisper"),
        [72] = new("Manbetsu Hanamaru", "Coquettish"),
        [73] = new("Manbetsu Hanamaru", "Boyish"),
        [74] = new("Kotoei Nia", "Normal"),
        [75] = new("Zundamon", "Exhausted"),
        [76] = new("Zundamon", "Tearful"),
        [77] = new("Mochiko-san", "Crying"),
        [78] = new("Mochiko-san", "Angry"),
        [79] = new("Mochiko-san", "Joy"),
        [80] = new("Mochiko-san", "Relaxed"),
        [81] = new("Aoyama Ryusei", "Passionate"),
        [82] = new("Aoyama Ryusei", "Grumpy"),
        [83] = new("Aoyama Ryusei", "Joy"),
        [84] = new("Aoyama Ryusei", "Gentle"),
        [85] = new("Aoyama Ryusei", "Sad"),
        [86] = new("Aoyama Ryusei", "Whisper"),
        [87] = new("Goki", "Human (angry) ver."),
        [88] = new("Goki", "Oni ver."),
        [89] = new("Voidoll", "Normal"),
        [90] = new("Zonko", "Normal"),
        [91] = new("Zonko", "Low energy"),
        [92] = new("Zonko", "Awakened"),
        [93] = new("Zonko", "Commentary style"),
        [94] = new("Chubu Tsurugi", "Normal"),
        [95] = new("Chubu Tsurugi", "Angry"),
        [96] = new("Chubu Tsurugi", "Hushed"),
        [97] = new("Chubu Tsurugi", "Anxious"),
        [98] = new("Chubu Tsurugi", "Despair & defeat"),
        [99] = new("Rito", "Normal"),
        [100] = new("Kurosawa Saishiro", "Normal"),
        [101] = new("Rito", "Serious"),
        [102] = new("Yuurei-chan", "Normal"),
        [103] = new("Yuurei-chan", "Sweet"),
        [104] = new("Yuurei-chan", "Sad"),
        [105] = new("Yuurei-chan", "Whisper"),
        [106] = new("Yuurei-chan", "Tsukumo-chan"),
        [107] = new("Tohoku Zunko", "Normal"),
        [108] = new("Tohoku Kiritan", "Normal"),
        [109] = new("Tohoku Itako", "Normal"),
        [110] = new("Nekomata Al", "Bold"),
        [111] = new("Nekomata Al", "Exhausted"),
        [112] = new("Nekomata Bii", "Bold"),
        [113] = new("Ankomon", "Normal"),
        [114] = new("Ankomon", "Bold"),
        [115] = new("Ankomon", "Soft"),
        [116] = new("Ankomon", "Lazy"),
        [117] = new("Ankomon", "Whisper"),
        [118] = new("Yogatari Tobari", "Normal"),
        [119] = new("Yogatari Tobari", "Bright"),
        [120] = new("Yogatari Tobari", "Sad"),
        [121] = new("Yogatari Tobari", "Exasperated"),
        [122] = new("Gyoki Mitama", "Normal"),
        [123] = new("Gyoki Mitama", "Angry"),
        [124] = new("Gyoki Mitama", "Sad"),
        [125] = new("Gyoki Mitama", "Whisper"),
        [126] = new("Rishii Yuka", "Bud"),
        [10000] = new("Male voice 2", "Normal"),
        [10001] = new("Male voice 1", "Normal"),
        [10002] = new("Male voice 3", "Normal"),
        [10003] = new("Female voice 4", "Normal"),
        [10004] = new("Female voice 3", "Normal"),
        [10005] = new("Female voice 1", "Normal"),
        [10006] = new("Female voice 6", "Normal"),
        [10007] = new("Female voice 2", "Normal"),
        [10008] = new("Female voice 5", "Normal"),
    };

    internal static bool TryGet(AppLanguage language, int styleId, out VoicevoxSpeakerStyleEntry entry)
    {
        entry = default;
        if (language == AppLanguage.Japanese)
            return false;

        return EnglishByStyleId.TryGetValue(styleId, out entry);
    }
}
